import type { PermissionKey } from '../types/auth';

export const PERMISSIONS = {
  assetsRead: 'assets.read',
  assetsCreate: 'assets.create',
  assetsUpdate: 'assets.update',
  assetsDelete: 'assets.delete',
  providersRead: 'providers.read',
  providersCreate: 'providers.create',
  providersUpdate: 'providers.update',
  providersDelete: 'providers.delete',
  aiProvidersRead: 'aiProviders.read',
  aiProvidersCreate: 'aiProviders.create',
  aiProvidersUpdate: 'aiProviders.update',
  aiProvidersDelete: 'aiProviders.delete',
  settingsRead: 'settings.read',
  settingsUpdate: 'settings.update',
  usersRead: 'users.read',
  usersCreate: 'users.create',
  usersUpdate: 'users.update',
  usersDisable: 'users.disable',
  usersManagePermissions: 'users.managePermissions',
} as const satisfies Record<string, PermissionKey>;

export const PERMISSION_OPTIONS = [
  PERMISSIONS.assetsRead,
  PERMISSIONS.assetsCreate,
  PERMISSIONS.assetsUpdate,
  PERMISSIONS.assetsDelete,
  PERMISSIONS.providersRead,
  PERMISSIONS.providersCreate,
  PERMISSIONS.providersUpdate,
  PERMISSIONS.providersDelete,
  PERMISSIONS.aiProvidersRead,
  PERMISSIONS.aiProvidersCreate,
  PERMISSIONS.aiProvidersUpdate,
  PERMISSIONS.aiProvidersDelete,
  PERMISSIONS.settingsRead,
  PERMISSIONS.settingsUpdate,
  PERMISSIONS.usersRead,
  PERMISSIONS.usersCreate,
  PERMISSIONS.usersUpdate,
  PERMISSIONS.usersDisable,
  PERMISSIONS.usersManagePermissions,
] as const;
